
type region = Record<string,string>
interface Test {
    [key: string] :region;
}

export const MapTranslator: Test = {
    en: { 
    //Список стран мира
        BD:	"Bangladesh",
        BE:	"Belgium",
        BF:	"Burkina Faso",
        BG:	"Bulgaria",
        BA:	"Bosnia and Herz.",
        BN:	"Brunei",
        BO:	"Bolivia",
        JP:	"Japan",
        BI:	"Burundi",
        BJ:	"Benin",
        BT:	"Bhutan",
        JM:	"Jamaica",
        BW:	"Botswana",
        BR:	"Brazil",
        BS:	"Bahamas",
        BY:	"Belarus",
        BZ:	"Belize",
        RU:	"Russia",
        RW:	"Rwanda",
        RS:	"Serbia",
        TL:	"Timor-Leste",
        TM:	"Turkmenistan",
        TJ:	"Tajikistan",
        RO:	"Romania",
        GW:	"Guinea-Bissau",
        GT:	"Guatemala",
        GR:	"Greece",
        GQ:	"Eq. Guinea",
        GY:	"Guyana",
        GE:	"Georgia",
        GB:	"United Kingdom",
        GA:	"Gabon",
        GN:	"Guinea",
        GM:	"Gambia",
        GL:	"Greenland",
        GH:	"Ghana",
        OM:	"Oman",
        TN:	"Tunisia",
        JO:	"Jordan",
        HR:	"Croatia",
        HT:	"Haiti",
        HU:	"Hungary",
        HN:	"Honduras",
        PR:	"Puerto Rico",
        PS:	"Palestine",
        PT:	"Portugal",
        PY:	"Paraguay",
        PA:	"Panama",
        PG:	"Papua New Guinea",
        PE:	"Peru",
        PK:	"Pakistan",
        PH:	"Philippines",
        PL:	"Poland",
        ZM:	"Zambia",
        EH:	"W. Sahara",
        EE:	"Estonia",
        EG:	"Egypt",
        ZA:	"South Africa",
        EC:	"Ecuador",
        IT:	"Italy",
        VN:	"Vietnam",
        SB:	"Solomon Is.",
        ET:	"Ethiopia",
        SO:	"Somalia",
        ZW:	"Zimbabwe",
        ES:	"Spain",
        ER:	"Eritrea",
        ME:	"Montenegro",
        MD:	"Moldova",
        MG:	"Madagascar",
        MA:	"Morocco",
        UZ:	"Uzbekistan",
        MM:	"Myanmar",
        ML:	"Mali",
        MN:	"Mongolia",
        MK:	"Macedonia",
        MW:	"Malawi",
        MR:	"Mauritania",
        UG:	"Uganda",
        MY:	"Malaysia",
        MX:	"Mexico",
        IL:	"Israel",
        FR:	"France",
        XS:	"Somaliland",
        FI:	"Finland",
        FJ:	"Fiji",
        FK:	"Falkland Is.",
        NI:	"Nicaragua",
        NL:	"Netherlands",
        NO:	"Norway",
        NA:	"Namibia",
        VU:	"Vanuatu",
        NC:	"New Caledonia",
        NE:	"Niger",
        NG:	"Nigeria",
        NZ:	"New Zealand",
        NP:	"Nepal",
        XK:	"Kosovo",
        CI:	"Côte d'Ivoire",
        CH:	"Switzerland",
        CO:	"Colombia",
        CN:	"China",
        CM:	"Cameroon",
        CL:	"Chile",
        XC:	"N. Cyprus",
        CA:	"Canada",
        CG:	"Congo",
        CF:	"Central African Rep.",
        CD:	"Dem. Rep. Congo",
        CZ:	"Czech Rep.",
        CY:	"Cyprus",
        CR:	"Costa Rica",
        CU:	"Cuba",
        SZ:	"Swaziland",
        SY:	"Syria",
        KG:	"Kyrgyzstan",
        KE:	"Kenya",
        SS:	"S. Sudan",
        SR:	"Suriname",
        KH:	"Cambodia",
        SV:	"El Salvador",
        SK:	"Slovakia",
        KR:	"Korea",
        SI:	"Slovenia",
        KP:	"Dem. Rep. Korea",
        KW:	"Kuwait",
        SN:	"Senegal",
        SL:	"Sierra Leone",
        KZ:	"Kazakhstan",
        SA:	"Saudi Arabia",
        SE:	"Sweden",
        SD:	"Sudan",
        DO:	"Dominican Rep.",
        DJ:	"Djibouti",
        DK:	"Denmark",
        DE:	"Germany",
        YE:	"Yemen",
        DZ:	"Algeria",
        US:	"United States",
        UY:	"Uruguay",
        LB:	"Lebanon",
        LA:	"Lao PDR",
        TW:	"Taiwan",
        TT:	"Trinidad and Tobago",
        TR:	"Turkey",
        LK:	"Sri Lanka",
        LV:	"Latvia",
        LT:	"Lithuania",
        LU:	"Luxembourg",
        LR:	"Liberia",
        LS:	"Lesotho",
        TH:	"Thailand",
        TF:	"Fr. S. Antarctic Lands",
        TG:	"Togo",
        TD:	"Chad",
        LY:	"Libya",
        AE:	"United Arab Emirates",
        VE:	"Venezuela",
        AF:	"Afghanistan",
        IQ:	"Iraq",
        IS:	"Iceland",
        IR:	"Iran",
        AM:	"Armenia",
        AL:	"Albania",
        AO:	"Angola",
        AR:	"Argentina",
        AU:	"Australia",
        AT:	"Austria",
        IN:	"India",
        TZ:	"Tanzania",
        AZ:	"Azerbaijan",
        IE:	"Ireland",
        ID:	"Indonesia",
        UA:	"Ukraine",
        QA:	"Qatar",
        MZ:	"Mozambique",
    //Список регионов России
        "RU-PNZ":	"Penzenskaya oblast",
        "RU-VLA":	"Vladimirskaya oblast",
        "RU-LEN":	"Leningradskaya oblast",
        "RU-SAK":	"Sakhalinskaya oblast",
        "RU-KYA":	"Krasnoyarskiy kray",
        "RU-UD":	"Udmurtskaya Respublika",
        "RU-IVA":	"Ivanovskaya oblast",
        "RU-LIP":	"Lipetskaya oblast",
        "RU-AST":	"Astrakhanskaya oblast",
        "RU-CE":	"Chechenskaya Respublika",
        "RU-KHA":	"Khabarovskiy kray",
        "RU-ORE":	"Orenburgskaya oblast",
        "RU-KIR":	"Kirovskaya oblast",
        "RU-BA":	"Bashkortostan, Respublika",
        "RU-NGR":	"Novgorodskaya oblast",
        "RU-KLU":	"Kaluzhskaya oblast",
        "RU-OMS":	"Omskaya oblast",
        "RU-SAR":	"Saratovskaya oblast",
        "RU-ORL":	"Orlovskaya oblast",
        "RU-STA":	"Stavropolskiy kray",
        "RU-SE":	"Severnaya Osetiya-Alaniya, Respublika",
        "RU-SAM":	"Samarskaya oblast",
        "RU-SA":	"Sakha, Respublika",
        "RU-SVE":	"Sverdlovskaya oblast",
        "RU-KK":	"Khakasiya, Respublika",
        "RU-SPE":	"Sankt-Peterburg",
        "RU-MOS":	"Moskovskaya oblast",
        "RU-BEL":	"Belgorodskaya oblast",
        "RU-KHM":	"Khanty-Mansiyskiy avtonomnyy okrug",
        "RU-VLG":	"Vologodskaya oblast",
        "RU-CHE":	"Chelyabinskaya oblast",
        "RU-YAR":	"Yaroslavskaya oblast",
        "RU-TUL":	"Tulskaya oblast",
        "RU-IRK":	"Irkutskaya oblast",
        "RU-NIZ":	"Nizhegorodskaya oblast",
        "RU-YAN":	"Yamalo-Nenetskiy avtonomnyy okrug",
        "RU-KGD":	"Kaliningradskaya oblast",
        "RU-MOW":	"Moskva",
        "RU-KAM":	"Kamchatskiy kray",
        "RU-BU":	"Buryatiya, Respublika",
        "RU-KEM":	"Kemerovskaya oblast",
        "RU-CHU":	"Chukotskiy avtonomnyy okrug",
        "RU-ULY":	"Ulyanovskaya oblast",
        "RU-KGN":	"Kurganskaya oblast",
        "RU-KRS":	"Kurskaya oblast",
        "RU-KR":	"Kareliya, Respublika",
        "RU-ME":	"Mariy El, Respublika",
        "RU-IN":	"Ingushetiya, Respublika",
        "RU-MAG":	"Magadanskaya oblast",
        "RU-MO":	"Mordoviya, Respublika",
        "RU-TA":	"Tatarstan, Respublika",
        "RU-ZAB":	"Zabaykalskiy kray",
        "RU-RYA":	"Ryazanskaya oblast",
        "RU-TAM":	"Tambovskaya oblast",
        "RU-ARK":	"Arkhangelskaya oblast",
        "RU-KC":	"Karachayevo-Cherkesskaya Respublika",
        "RU-TY":	"Tyva, Respublika [Tuva]",
        "RU-MUR":	"Murmanskaya oblast",
        "RU-VOR":	"Voronezhskaya oblast",
        "RU-PSK":	"Pskovskaya oblast",
        "RU-TVE":	"Tverskaya oblast",
        "RU-VGG":	"Volgogradskaya oblast",
        "RU-KOS":	"Kostromskaya oblast",
        "RU-KL":	"Kalmykiya, Respublika",
        "RU-TOM":	"Tomskaya oblast",
        "RU-KO":	"Komi, Respublika",
        "RU-TYU":	"Tyumenskaya oblast",
        "RU-DA":	"Dagestan, Respublika",
        "RU-NVS":	"Novosibirskaya oblast",
        "RU-AD":	"Adygeya, Respublika",
        "RU-PER":	"Permskiy kray",
        "RU-ROS":	"Rostovskaya oblast",
        "RU-PRI":	"Primorskiy kray",
        "RU-KB":	"Kabardino-Balkarskaya Respublika",
        "RU-AL":	"Altay, Respublika",
        "RU-NEN":	"Nenetskiy avtonomnyy okrug",
        "RU-ALT":	"Altayskiy kray",
        "RU-KDA":	"Krasnodarskiy kray",
    	"RU-YEV":	"Yevreyskaya avtonomnaya oblast",
        "RU-AMU":	"Amurskaya oblast",
        "RU-BRY":	"Bryanskaya oblast",
        "RU-SMO":	"Smolenskaya oblast",
        "RU-CU": "Chuvashskaya Respublika"
    },
    ru: { 
    //Список стран мира
    BD:	"Бангладеш",
    BE:	"Бельгия",
    BF:	"Буркина-Фасо",
    BG:	"Болгария",
    BA:	"Босния и Герцеговина",
    BN:	"Бруней-Даруссалам",
    BO:	"Боливия",
    JP:	"Япония",
    BI:	"Бурунди",
    BJ:	"Бенин",
    BT:	"Бутан",
    JM:	"Ямайка",
    BW:	"Ботсвана",
    BR:	"Бразилия",
    BS:	"Багамы",
    BY:	"Беларусь",
    BZ:	"Белиз",
    RU:	"Россия",
    RW:	"Руанда",
    RS:	"Сербия",
    TL:	"Тимор-Лесте",
    TM:	"Туркмения",
    TJ:	"Таджикистан",
    RO:	"Румыния",
    GW:	"Гвинея-Бисау",
    GT:	"Гватемала",
    GR:	"Греция",
    GQ:	"Экваториальная Гвинея",
    GY:	"Гайана",
    GE:	"Грузия",
    GB:	"Соединенное Королевство",
    GA:	"Габон",
    GN:	"Гвинея",
    GM:	"Гамбия",
    GL:	"Гренландия",
    GH:	"Гана",
    OM:	"Оман",
    TN:	"Тунис",
    JO:	"Иордания",
    HR:	"Хорватия",
    HT:	"Гаити",
    HU:	"Венгрия",
    HN:	"Гондурас",
    PR:	"Пуэрто-Рико",
    PS:	"Палестинская территория",
    PT:	"Португалия",
    PY:	"Парагвай",
    PA:	"Панама",
    PG:	"Папуа-Новая Гвинея",
    PE:	"Перу",
    PK:	"Пакистан",
    PH:	"Филиппины",
    PL:	"Польша",
    ZM:	"Замбия",
    EH:	"Западная Сахара",
    EE:	"Эстония",
    EG:	"Египет",
    ZA:	"Южная Африка",
    EC:	"Эквадор",
    IT:	"Италия",
    VN:	"Вьетнам",
    SB:	"Соломоновы острова",
    ET:	"Эфиопия",
    SO:	"Сомали",
    ZW:	"Зимбабве",
    ES:	"Испания",
    ER:	"Эритрея",
    ME:	"Черногория",
    MD:	"Молдова, Республика",
    MG:	"Мадагаскар",
    MA:	"Марокко",
    UZ:	"Узбекистан",
    MM:	"Мьянма",
    ML:	"Мали",
    MN:	"Монголия",
    MK:	"Республика Македония",
    MW:	"Малави",
    MR:	"Мавритания",
    UG:	"Уганда",
    MY:	"Малайзия",
    MX:	"Мексика",
    IL:	"Израиль",
    FR:	"Франция",
    XS:	"Сомали",
    FI:	"Финляндия",
    FJ:	"Фиджи",
    FK:	"Фолклендские острова (Мальвинские)",
    NI:	"Никарагуа",
    NL:	"Нидерланды",
    NO:	"Норвегия",
    NA:	"Намибия",
    VU:	"Вануату",
    NC:	"Новая Каледония",
    NE:	"Нигер",
    NG:	"Нигерия",
    NZ:	"Новая Зеландия",
    NP:	"Непал",
    XK:	"Косово",
    CI:	"Кот д'Ивуар",
    CH:	"Швейцария",
    CO:	"Колумбия",
    CN:	"Китай",
    CM:	"Камерун",
    CL:	"Чили",
    XC:	"Северный Кипр",
    CA:	"Канада",
    CG:	"Конго",
    CF:	"Центрально-Африканская Республика",
    CD:	"Конго, Демократическая Республика",
    CZ:	"Чешская Республика",
    CY:	"Кипр",
    CR:	"Коста-Рика",
    CU:	"Куба",
    SZ:	"Свазиленд",
    SY:	"Сирия",
    KG:	"Киргизия",
    KE:	"Кения",
    SS:	"Южный Судан",
    SR:	"Суринам",
    KH:	"Камбоджа",
    SV:	"Эль-Сальвадор",
    SK:	"Словакия",
    KR:	"Корея, Республикаa",
    SI:	"Словения",
    KP:	"Корея, Народно-Демократическая Республика",
    KW:	"Кувейт",
    SN:	"Сенегал",
    SL:	"Сьерра-Леоне",
    KZ:	"Казахстан",
    SA:	"Саудовская Аравия",
    SE:	"Швеция",
    SD:	"Судан",
    DO:	"Доминиканская Республика",
    DJ:	"Джибути",
    DK:	"Дания",
    DE:	"Германия",
    YE:	"Йемен",
    DZ:	"Алжир",
    US:	"Соединенные Штаты",
    UY:	"Уругвай",
    LB:	"Ливан",
    LA:	"Лаос",
    TW:	"Тайвань (Китай)",
    TT:	"Тринидад и Тобаго",
    TR:	"Турция",
    LK:	"Шри-Ланка",
    LV:	"Латвия",
    LT:	"Литва",
    LU:	"Люксембург",
    LR:	"Либерия",
    LS:	"Лесото",
    TH:	"Таиланд",
    TF:	"Французские Южные территории",
    TG:	"Того",
    TD:	"Чад",
    LY:	"Ливийская Арабская Джамахирия",
    AE:	"Объединенные Арабские Эмираты",
    VE:	"Венесуэла Боливарианская Республика",
    AF:	"Афганистан",
    IQ:	"Ирак",
    IS:	"Исландия",
    IR:	"Иран, Исламская Республика",
    AM:	"Армения",
    AL:	"Албания",
    AO:	"Ангола",
    AR:	"Аргентина",
    AU:	"Австралия",
    AT:	"Австрия",
    IN:	"Индия",
    TZ:	"Танзания",
    AZ:	"Азербайджан",
    IE:	"Ирландия",
    ID:	"Индонезия",
    UA:	"Украина",
    QA:	"Катар",
    MZ:	"Мозамбик",
//Список регионов России
    "RU-PNZ":	"Пензенская область",
    "RU-VLA":	"Владимирская область",
    "RU-LEN":	"Ленинградская область",
    "RU-SAK":	"Сахалинская область",
    "RU-KYA":	"Красноярский край",
    "RU-UD":	"Удмуртская Республика",
    "RU-IVA":	"Ивановская область",
    "RU-LIP":	"Липецкая область",
    "RU-AST":	"Астраханская область",
    "RU-CE":	"Чеченская республика",
    "RU-KHA":	"Хабаровский край",
    "RU-ORE":	"Оренбургская область",
    "RU-KIR":	"Кировская область",
    "RU-BA":	"Республика Башкортостан",
    "RU-NGR":	"Новгородская область",
    "RU-KLU":	"Калужская область",
    "RU-OMS":	"Омская область",
    "RU-SAR":	"Саратовская область",
    "RU-ORL":	"Орловская область",
    "RU-STA":	"Ставропольский край",
    "RU-SE":	"Республика Северная Осетия — Алания",
    "RU-SAM":	"Самарская область",
    "RU-SA":	"Республика Саха (Якутия)",
    "RU-SVE":	"Свердловская область",
    "RU-KK":	"Республика Хакасия",
    "RU-SPE":	"г. Санкт-Петербург",
    "RU-MOS":	"Московская область",
    "RU-BEL":	"Белгородская область",
    "RU-KHM":	"Ханты-Мансийский автономный округ - Югра",
    "RU-VLG":	"Вологодская область",
    "RU-CHE":	"Челябинская область",
    "RU-YAR":	"Ярославская область",
    "RU-TUL":	"Тульская область",
    "RU-IRK":	"Иркутская область",
    "RU-NIZ":	"Нижегородская область",
    "RU-YAN":	"Ханты-Мансийский автономный округ — Югра",
    "RU-KGD":	"Калининградская область",
    "RU-MOW":	"г. Москва",
    "RU-KAM":	"Камчатский край",
    "RU-BU":	"Республика Бурятия",
    "RU-KEM":	"Кемеровская область",
    "RU-CHU":	"Чукотский автономный округ",
    "RU-ULY":	"Ульяновская область",
    "RU-KGN":	"Курганская область",
    "RU-KRS":	"Курская область",
    "RU-KR":	"Республика Карелия",
    "RU-ME":	"Республика Марий Эл",
    "RU-IN":	"Республика Ингушетия",
    "RU-MAG":	"Магаданская область",
    "RU-MO":	"Республика Мордовия",
    "RU-TA":	"Республика Татарстан",
    "RU-ZAB":	"Забайкальский край",
    "RU-RYA":	"Рязанская область",
    "RU-TAM":	"Тамбовская область",
    "RU-ARK":	"Тамбовская область",
    "RU-KC":	"Республика Карачаево-Черкессия",
    "RU-TY":	"Республика Тыва",
    "RU-MUR":	"Мурманская область",
    "RU-VOR":	"Воронежская область",
    "RU-PSK":	"Воронежская область",
    "RU-TVE":	"Тверская область",
    "RU-VGG":	"Вологодская область",
    "RU-KOS":	"Костромская область",
    "RU-KL":	"Республика Калмыкия",
    "RU-TOM":	"Томская область",
    "RU-KO":	"Республика Коми",
    "RU-TYU":	"Тюменская область",
    "RU-DA":	"Республика Дагестан",
    "RU-NVS":	"Новосибирская область",
    "RU-AD":	"Республика Адыгея",
    "RU-PER":	"Пермский край",
    "RU-ROS":	"Ростовская область",
    "RU-PRI":	"Приморский край",
    "RU-KB":	"Кабардино-Балкарская Республика",
    "RU-AL":	"Республика Алтай (Горный Алтай)",
    "RU-NEN":	"Ненецкий автономный округ",
    "RU-ALT":	"Алтайский край",
    "RU-KDA":	"Краснодарский край",
    "RU-YEV":	"Еврейская автономная область",
    "RU-AMU":	"Амурская область",
    "RU-BRY":	"Брянская область",
    "RU-SMO":	"Смоленская область",
    "RU-CU": "Чувашская Республика"
    }
}
